# Step 1: Base image for dependencies
FROM continuumio/miniconda3:latest AS base

# Specify Python version and set environment variables
ENV PYTHON_VERSION=3.10
ARG DEBIAN_FRONTEND=noninteractive

# Update and install essential packages
RUN apt-get update && \
    apt-get install -y bash curl git wget software-properties-common

# Create Conda environment
RUN conda create --name conda python=${PYTHON_VERSION} pip

# Upgrade pip
RUN /opt/conda/envs/conda/bin/pip install --no-cache-dir --upgrade pip

RUN git clone https://github.com/PsychoLogicAu/flickr_scraper.git

# Set working directory
WORKDIR /flickr_scraper
RUN git fetch
RUN git pull

# Activate Conda environment and install necessary packages
RUN /opt/conda/bin/conda run -n conda pip install -U -r requirements.txt

# Bugfix for flickrapi:
COPY fixed_flickr_scraper_core.py /opt/conda/envs/conda/lib/python3.10/site-packages/flickrapi/core.py

# Step 2: Final image
FROM ubuntu:22.04

# Set non-interactive frontend
ARG DEBIAN_FRONTEND=noninteractive

# Install essential packages
RUN apt-get update && \
    apt-get install -y bash curl git wget software-properties-common && \
    apt-get install -y libgl1 gnupg2 moreutils tk libglib2.0-0 libaio-dev && \
    apt-get install -y unzip

# Install git-lfs
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    apt-get install -y git-lfs && \
    git lfs install

# Create user and set permissions
ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

USER $USERNAME

# Copy Conda environment from dependencies stage
COPY --from=base /opt/conda /opt/conda

# Copy the Flickr Scraper repository, and update the owner and permissions of the directory
COPY --from=base /flickr_scraper /flickr_scraper
USER root
RUN chown -R $USERNAME:$USERNAME /flickr_scraper
USER $USERNAME

ARG PIP_EXTRA
ENV PIP_EXTRA=$PIP_EXTRA
# if PIP_EXTRA is not empty, install the extra packages
RUN test -z "$PIP_EXTRA" || /opt/conda/bin/conda run -n conda pip install --no-cache-dir ${PIP_EXTRA}

# Set environment variables
ENV PATH /opt/conda/bin:$PATH

# Skip downloading large files with Git LFS
ENV GIT_LFS_SKIP_SMUDGE=1

# Copy the file set_flickr_api_creds.sh to the working directory
COPY set_flickr_api_creds.sh /

# Write the entrypoint.sh script
USER root
RUN echo '#!/bin/bash' > /entrypoint.sh
RUN echo 'source activate conda' >> /entrypoint.sh
RUN echo 'source set_flickr_api_creds.sh' >> /entrypoint.sh
RUN echo 'cd /data/flickr_scraper' >> /entrypoint.sh
RUN echo 'python3 /flickr_scraper/flickr_scraper.py --download --n $1 --search \"$2\"' >> /entrypoint.sh
RUN chmod +x /entrypoint.sh
USER $USERNAME

# Set entrypoint to activate Conda environment, set Flickr API credentials, and start a bash shell
# ENTRYPOINT ["/bin/bash", "-c", "source activate conda && source set_flickr_api_creds.sh && cd /data/flickr_scraper && python3 /flickr_scraper/flickr_scraper.py --download --n \"$1\" --search \"$2\""]

ENTRYPOINT ["/entrypoint.sh"]
